remote_theme: pages-themes/minimal@v0.2.0
title: Jacob Fredegaard Hansen
description: Personal portfolio of various projects.
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/