remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Jacob Fredegaard Hansen
description: Personal portfolio of various projects.
plugins:
  - jekyll-include-cache

main:
  - title: "Home"
    url: /
    weight: 1
  - title: "About"
    url: /about/
    weight: 2
  - title: "Projects"
    url: /projects/
    weight: 4
